# Generated by Django 5.1.1 on 2024-09-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_user_profile',
            field=models.IntegerField(default=6, null=True),
        ),
    ]
