# Generated by Django 5.1.1 on 2024-09-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_profile_age_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='age_user_profile',
            new_name='age',
        ),
    ]
