# Generated by Django 5.1.1 on 2024-09-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_rename_age_user_profile_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/defuser/user.jpeg', upload_to='imageuser/'),
        ),
    ]
