# Generated by Django 5.1.1 on 2024-09-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
