# Generated by Django 5.1.1 on 2024-09-06 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shippingsdress_order', to='order.order')),
            ],
            options={
                'verbose_name': 'shippingadress',
                'verbose_name_plural': 'shippingadress',
                'db_table': 'ShippingAdress',
            },
        ),
    ]
